### ISSUE TITLE
按照指引，用普通用户 clone 了仓库，但是中途权限被破坏了

### ISSUE THREAD

**Issue by flw-cn** [Dieken/ZMOS#2]
操作指引中有一步需要用 root 身份运行，运行之后权限就变了，所以后续的 pull 都只能用 root 进行。

**Comment by Dieken** [comment]
复现不了，可能是在切换到 root 后执行了 git status/pull 操作，导致把 .git/index,  .git/objects/xxx 变成 root 账户的文件了，之后切换到普通用户执行 git 就会失败。
