### ISSUE TITLE
每次 pkg install 都会先 update 一次 FreeBSD repository catalogue，不知道为什么

### ISSUE THREAD

**Issue by flw-cn** [Dieken/ZMOS#3]
也不知道如何诊断

**Comment by Dieken** [comment]
这个问题很容易调查，无非是 pkg 配置，它的配置在 /etc/pkg* 和 /usr/local/etc/pkg* 下，搜索 update 就能找到了，man pkg.conf 搜索 automatically 字样也能很快找到。

解决办法是修改 /usr/local/etc/pkg.conf, 把 REPO_AUTOUPDATE: 设置成 false。

**Comment by Dieken** [comment]
这么设置后，就要时不时手动 pkg update 更新软件包索引，跟 Debian 的 apt update 类似。
